# Generated by Django 5.1.5 on 2025-01-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_otpstorage_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OTPStorage",
        ),
    ]
