# Generated by Django 5.1.5 on 2025-01-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0003_delete_otpstorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="mp3file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mp3",
                to="pdf.mp3file",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="pdf.profile",
            ),
        ),
    ]
